//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18033
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taipei_YouBike_WP7.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taipei_YouBike_WP7.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 terms &amp; about 的當地語系化字串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 add 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input a bike stop name 的當地語系化字串。
        /// </summary>
        public static string AddFavePageSearchBoxHint {
            get {
                return ResourceManager.GetString("AddFavePageSearchBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add a favorite bike stop: 的當地語系化字串。
        /// </summary>
        public static string AddFavPageTitle {
            get {
                return ResourceManager.GetString("AddFavPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 maps view 的當地語系化字串。
        /// </summary>
        public static string AppBarMaps {
            get {
                return ResourceManager.GetString("AppBarMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 my location 的當地語系化字串。
        /// </summary>
        public static string AppBarMyLocation {
            get {
                return ResourceManager.GetString("AppBarMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I Love YouBike 的當地語系化字串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address: 的當地語系化字串。
        /// </summary>
        public static string BikeStopAddressTitle {
            get {
                return ResourceManager.GetString("BikeStopAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Available: 的當地語系化字串。
        /// </summary>
        public static string BikeStopAvailableTitle {
            get {
                return ResourceManager.GetString("BikeStopAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Capacity: 的當地語系化字串。
        /// </summary>
        public static string BikeStopCapacityTitle {
            get {
                return ResourceManager.GetString("BikeStopCapacityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 District: 的當地語系化字串。
        /// </summary>
        public static string BikeStopDistrictTitle {
            get {
                return ResourceManager.GetString("BikeStopDistrictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 favorite 的當地語系化字串。
        /// </summary>
        public static string BikeStopFavoriteButton {
            get {
                return ResourceManager.GetString("BikeStopFavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map: 的當地語系化字串。
        /// </summary>
        public static string BikeStopMapsTitle {
            get {
                return ResourceManager.GetString("BikeStopMapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bike Stop 的當地語系化字串。
        /// </summary>
        public static string BikeStopPageTitle {
            get {
                return ResourceManager.GetString("BikeStopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 refresh 的當地語系化字串。
        /// </summary>
        public static string BikeStopRefreshButton {
            get {
                return ResourceManager.GetString("BikeStopRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 unfavorite 的當地語系化字串。
        /// </summary>
        public static string BikeStopUnfavoriteButton {
            get {
                return ResourceManager.GetString("BikeStopUnfavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Distance: 的當地語系化字串。
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This stop has been added to the favorite list. 的當地語系化字串。
        /// </summary>
        public static string FavoriteAdded {
            get {
                return ResourceManager.GetString("FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This stop has been removed from the favorite list. 的當地語系化字串。
        /// </summary>
        public static string FavoriteRemoved {
            get {
                return ResourceManager.GetString("FavoriteRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading... 的當地語系化字串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading data... 的當地語系化字串。
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading from Internet... 的當地語系化字串。
        /// </summary>
        public static string LoadingFromInternet {
            get {
                return ResourceManager.GetString("LoadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Locating your position... 的當地語系化字串。
        /// </summary>
        public static string Locating {
            get {
                return ResourceManager.GetString("Locating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This app would use the GPS and network to find your location to provide you the information about YouBike. You can configure it on/off in the settings page. 的當地語系化字串。
        /// </summary>
        public static string LocationConsent {
            get {
                return ResourceManager.GetString("LocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning: Tracking Privacy 的當地語系化字串。
        /// </summary>
        public static string LocationConsentCaption {
            get {
                return ResourceManager.GetString("LocationConsentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 meters 的當地語系化字串。
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot read content through Internet now! Please check the network status and re-try later. 的當地語系化字串。
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Network error 的當地語系化字串。
        /// </summary>
        public static string NetworkErrorCaption {
            get {
                return ResourceManager.GetString("NetworkErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 off 的當地語系化字串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 YouBike official site 的當地語系化字串。
        /// </summary>
        public static string OfficialSiteTitle {
            get {
                return ResourceManager.GetString("OfficialSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 on 的當地語系化字串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Favorited Stops 的當地語系化字串。
        /// </summary>
        public static string PanoFirst {
            get {
                return ResourceManager.GetString("PanoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Near Stops 的當地語系化字串。
        /// </summary>
        public static string PanoNear {
            get {
                return ResourceManager.GetString("PanoNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About the app 的當地語系化字串。
        /// </summary>
        public static string PanoOther {
            get {
                return ResourceManager.GetString("PanoOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 privacy 的當地語系化字串。
        /// </summary>
        public static string PrivacyDeclaration {
            get {
                return ResourceManager.GetString("PrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rate this app! 的當地語系化字串。
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 refresh 的當地語系化字串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LeftToRight 的當地語系化字串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 en-US 的當地語系化字串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sample Runtime Property Value 的當地語系化字串。
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 settings 的當地語系化字串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use your location 的當地語系化字串。
        /// </summary>
        public static string SettingsPageTrackHeader {
            get {
                return ResourceManager.GetString("SettingsPageTrackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Terms 的當地語系化字串。
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All data in this app are fetched from http://www.youbike.com.tw/ and they belongs to Taiwan GIANT Sales Company. 的當地語系化字串。
        /// </summary>
        public static string toc {
            get {
                return ResourceManager.GetString("toc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You&apos;ve disabled the &quot;Use your location&quot; option. To use this feature, please enable the &quot;Use your location&quot; option in the settings page so that it will not show you the result of near stops. 的當地語系化字串。
        /// </summary>
        public static string TrackingOff {
            get {
                return ResourceManager.GetString("TrackingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 version: 的當地語系化字串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
