//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taipei_YouBike_WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                  global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taipei_YouBike_WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms &amp; about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a bike stop name.
        /// </summary>
        public static string AddFavePageSearchBoxHint {
            get {
                return ResourceManager.GetString("AddFavePageSearchBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a favorite bike stop:.
        /// </summary>
        public static string AddFavPageTitle {
            get {
                return ResourceManager.GetString("AddFavPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps view.
        /// </summary>
        public static string AppBarMaps {
            get {
                return ResourceManager.GetString("AppBarMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my location.
        /// </summary>
        public static string AppBarMyLocation {
            get {
                return ResourceManager.GetString("AppBarMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Love YouBike.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string BikeStopAddressTitle {
            get {
                return ResourceManager.GetString("BikeStopAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available:.
        /// </summary>
        public static string BikeStopAvailableTitle {
            get {
                return ResourceManager.GetString("BikeStopAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity:.
        /// </summary>
        public static string BikeStopCapacityTitle {
            get {
                return ResourceManager.GetString("BikeStopCapacityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District:.
        /// </summary>
        public static string BikeStopDistrictTitle {
            get {
                return ResourceManager.GetString("BikeStopDistrictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        public static string BikeStopFavoriteButton {
            get {
                return ResourceManager.GetString("BikeStopFavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map:.
        /// </summary>
        public static string BikeStopMapsTitle {
            get {
                return ResourceManager.GetString("BikeStopMapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike Stop.
        /// </summary>
        public static string BikeStopPageTitle {
            get {
                return ResourceManager.GetString("BikeStopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string BikeStopRefreshButton {
            get {
                return ResourceManager.GetString("BikeStopRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfavorite.
        /// </summary>
        public static string BikeStopUnfavoriteButton {
            get {
                return ResourceManager.GetString("BikeStopUnfavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stop has been added to the favorite list..
        /// </summary>
        public static string FavoriteAdded {
            get {
                return ResourceManager.GetString("FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stop has been removed from the favorite list..
        /// </summary>
        public static string FavoriteRemoved {
            get {
                return ResourceManager.GetString("FavoriteRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading from Internet....
        /// </summary>
        public static string LoadingFromInternet {
            get {
                return ResourceManager.GetString("LoadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating your position....
        /// </summary>
        public static string Locating {
            get {
                return ResourceManager.GetString("Locating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app would use the GPS and network to find your location to provide you the information about YouBike. You can configure it on/off in the settings page..
        /// </summary>
        public static string LocationConsent {
            get {
                return ResourceManager.GetString("LocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Tracking Privacy.
        /// </summary>
        public static string LocationConsentCaption {
            get {
                return ResourceManager.GetString("LocationConsentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read content through Internet now! Please check the network status and re-try later..
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        public static string NetworkErrorCaption {
            get {
                return ResourceManager.GetString("NetworkErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouBike official site.
        /// </summary>
        public static string OfficialSiteTitle {
            get {
                return ResourceManager.GetString("OfficialSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited Stops.
        /// </summary>
        public static string PanoFirst {
            get {
                return ResourceManager.GetString("PanoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Stops.
        /// </summary>
        public static string PanoNear {
            get {
                return ResourceManager.GetString("PanoNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the app.
        /// </summary>
        public static string PanoOther {
            get {
                return ResourceManager.GetString("PanoOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy.
        /// </summary>
        public static string PrivacyDeclaration {
            get {
                return ResourceManager.GetString("PrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app!.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your location.
        /// </summary>
        public static string SettingsPageTrackHeader {
            get {
                return ResourceManager.GetString("SettingsPageTrackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data in this app are fetched from http://www.youbike.com.tw/ and they belongs to Taiwan GIANT Sales Company..
        /// </summary>
        public static string toc {
            get {
                return ResourceManager.GetString("toc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve disabled the &quot;Use your location&quot; option. To use this feature, please enable the &quot;Use your location&quot; option in the settings page so that it will not show you the result of near stops..
        /// </summary>
        public static string TrackingOff {
            get {
                return ResourceManager.GetString("TrackingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
